#!/bin/bash

load inquirer

check() {
  if [ ! -f $SERVICE_CONFIG ]; then
     touch $SERVICE_CONFIG
  fi
  config::load_file $SERVICE_CONFIG

  if [ -z "$SERVICE_DRONE_GOGS_DOMAIN" ]; then
    inquirer::text "请输入 SERVICE_DRONE_GOGS_DOMAIN:" value
    config::set SERVICE_DRONE_GOGS_DOMAIN $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_DRONE_DOMAIN" ]; then
    inquirer::text "请输入 SERVICE_DRONE_DOMAIN:" value
    config::set SERVICE_DRONE_DOMAIN $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_DRONE_RPC_SECRET" ]; then
    inquirer::text "请输入 SERVICE_DRONE_RPC_SECRET:" value
    config::set SERVICE_DRONE_RPC_SECRET $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_DRONE_ADMIN_USER" ]; then
    inquirer::text "请输入 SERVICE_DRONE_ADMIN_USER:" value
    config::set SERVICE_DRONE_ADMIN_USER $value $SERVICE_CONFIG
  fi
  
  # load again
  config::load_file $SERVICE_CONFIG
  
  # @TODO
  export SERVICE_DRONE_GOGS_DOMAIN=$SERVICE_DRONE_GOGS_DOMAIN
  export SERVICE_DRONE_DOMAIN=$SERVICE_DRONE_DOMAIN
  export SERVICE_DRONE_RPC_SECRET=$SERVICE_DRONE_RPC_SECRET
  export SERVICE_DRONE_ADMIN_USER=$SERVICE_DRONE_ADMIN_USER
}

check $@
